import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const options = {
  method: "GET",
  headers: {
    "X-RapidAPI-Key": "3e41700525mshd63d73d318ce3a2p12f080jsn051459481d11",
    "X-RapidAPI-Host": "spotify-monthly-listeners.p.rapidapi.com",
  },
};

/*fetch("https://spotify-monthly-listeners.p.rapidapi.com/", options)
  .then((response) => response.json())
  .then((response) => response.map((artist) => <p>{artist.name}</p>))
  .catch((err) => console.error(err));*/

export async function getStaticProps() {
  const res = await fetch(
    "https://spotify-monthly-listeners.p.rapidapi.com/",
    options
  );
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Rapository</h1>
        
        {
          data.map((artist) => <p>{artist.artist}</p>)
        }

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
